### ISSUE TITLE
how to generates the ....

### ISSUE THREAD

**Issue by SeekPoint** [hiroki13/neural-semantic-role-labeler#3]
conll2005.train.txt
conll2005.test.txt
conll2005.dev.txt

**Comment by hiroki13** [comment]
These files are based on the Wall Street Journal sections 02-21 and 24 of the Penn Treebank II collection.
So, we have to get the Penn Treebank II collection in the following URL:
https://catalog.ldc.upenn.edu/LDC95T7

Unfortunately, it's not free.
Once you get it, you can convert the data to the conll2005 format using the software here:
http://www.cs.upc.edu/~srlconll/soft.html

**Comment by SeekPoint** [comment]
so, would you share it on non-commercial purpose?

**Comment by hiroki13** [comment]
The license does not allow us to share it:
https://catalog.ldc.upenn.edu/license/ldc-non-members-agreement.pdf

Sorry for that.
